=== pmgj/Eleicoes/Eleicoes.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="eleicao">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element name="candidatos" type="tCandidatos" minOccurs="1" maxOccurs="1" />
                <xs:element name="turno" type="tTurno" minOccurs="1" maxOccurs="2" />
            </xs:choice>
        </xs:complexType>
        <xs:key name="numero">
            <xs:selector xpath="candidatos/candidato"/>
            <xs:field xpath="@n"/>
        </xs:key>
        <xs:keyref name="numero_ref" refer="numero">
            <xs:selector xpath="turno/votacao/votos" />
            <xs:field xpath="@n" />
        </xs:keyref>    
    </xs:element>
    <xs:complexType name="tCandidatos">
        <xs:sequence>
            <xs:element name="candidato" type="tCandidato" maxOccurs="unbounded"/>            
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tTurno">
        <xs:sequence>
            <xs:element name="votacao" type="tVotacao" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="n">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="2"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="tCandidato">
        <xs:attribute name="n">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="99"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="nome" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="tVotacao">
        <xs:sequence>
            <xs:element name="votos" type="tVotos" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="brancos" type="xs:positiveInteger" />
        <xs:attribute name="nulos" type="xs:positiveInteger" />
        <xs:attribute name="abstencao" type="xs:positiveInteger" />
        <xs:attribute name="estado">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ac" />
                    <xs:enumeration value="am" />
                    <xs:enumeration value="ap" />
                    <xs:enumeration value="ba" />
                    <xs:enumeration value="ce" />
                    <xs:enumeration value="ro" />
                    <xs:enumeration value="rr" />
                    <xs:enumeration value="to" />
                    <xs:enumeration value="pa" />
                    <xs:enumeration value="al" />
                    <xs:enumeration value="se" />
                    <xs:enumeration value="pe" />
                    <xs:enumeration value="pb" />
                    <xs:enumeration value="rn" />
                    <xs:enumeration value="ce" />
                    <xs:enumeration value="pi" />
                    <xs:enumeration value="ma" />
                    <xs:enumeration value="sp" />
                    <xs:enumeration value="mg" />
                    <xs:enumeration value="rj" />
                    <xs:enumeration value="es" />
                    <xs:enumeration value="df" />
                    <xs:enumeration value="mt" />
                    <xs:enumeration value="ms" />
                    <xs:enumeration value="go" />
                    <xs:enumeration value="rs" />
                    <xs:enumeration value="sc" />
                    <xs:enumeration value="pr" />
                    <xs:enumeration value="vt" />
                    <xs:enumeration value="zz" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="tVotos">
        <xs:attribute name="n">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="99"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="votos" type="xs:nonNegativeInteger" />
    </xs:complexType>
</xs:schema>

=== pmgj/Eleicoes/Eleicao1998-Presidente.xml
<?xml version="1.0" encoding="UTF-8"?>
<eleicao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Eleicoes.xsd">
    <candidatos>
        <candidato n="13" nome="Lula"/>
        <candidato n="16" nome="Zé Maria"/>
        <candidato n="19" nome="Thereza Ruiz"/>
        <candidato n="20" nome="Sérgio Bueno"/>
        <candidato n="23" nome="Ciro Gomes"/>
        <candidato n="27" nome="José Maria Eymael"/>
        <candidato n="31" nome="Vasco Azevedo Neto"/>
        <candidato n="33" nome="Ivan Moacyr da Frota"/>
        <candidato n="43" nome="Alfredo Sirkis"/>
        <candidato n="45" nome="Fernando Henrique Cardoso"/>
        <candidato n="56" nome="Enéas Carneiro"/>
        <candidato n="70" nome="João de Deus"/>
    </candidatos>
    <turno n="1">
        <votacao estado="ac" brancos="17538" nulos="28979">
            <votos n="20" votos="283"/>
            <votos n="43" votos="808"/>
            <votos n="45" votos="90363"/>
            <votos n="19" votos="467"/>
            <votos n="56" votos="10362"/>
            <votos n="31" votos="603"/>
            <votos n="70" votos="972"/>
            <votos n="23" votos="26909"/>
            <votos n="33" votos="1461"/>
            <votos n="16" votos="655"/>
            <votos n="13" votos="59690"/>
            <votos n="27" votos="508"/>
        </votacao>
        <votacao estado="al" brancos="62821" nulos="209661">
            <votos n="45" votos="394873"/>
            <votos n="19" votos="915"/>
            <votos n="56" votos="6664"/>
            <votos n="23" votos="146729"/>
            <votos n="33" votos="4064"/>
            <votos n="16" votos="1385"/>
            <votos n="13" votos="161584"/>
            <votos n="27" votos="371"/>
            <votos n="20" votos="467"/>
            <votos n="43" votos="1317"/>
            <votos n="31" votos="1173"/>
            <votos n="70" votos="1111"/>
        </votacao>
        <votacao estado="am" brancos="49393" nulos="93256">
            <votos n="45" votos="452244"/>
            <votos n="56" votos="16094"/>
            <votos n="19" votos="2726"/>
            <votos n="23" votos="128820"/>
            <votos n="33" votos="3308"/>
            <votos n="16" votos="2765"/>
            <votos n="13" votos="211517"/>
            <votos n="27" votos="2689"/>
            <votos n="20" votos="1209"/>
            <votos n="43" votos="2506"/>
            <votos n="31" votos="959"/>
            <votos n="70" votos="2162"/>
        </votacao>
        <votacao estado="ap" brancos="2397" nulos="20633">
            <votos n="45" votos="68277"/>
            <votos n="19" votos="588"/>
            <votos n="56" votos="3237"/>
            <votos n="23" votos="25349"/>
            <votos n="33" votos="129"/>
            <votos n="16" votos="445"/>
            <votos n="13" votos="62394"/>
            <votos n="27" votos="60"/>
            <votos n="20" votos="226"/>
            <votos n="43" votos="324"/>
            <votos n="31" votos="102"/>
            <votos n="70" votos="187"/>
        </votacao>
        <votacao estado="ba" brancos="767837" nulos="752775">
            <votos n="20" votos="15694"/>
            <votos n="43" votos="13998"/>
            <votos n="45" votos="1978798"/>
            <votos n="56" votos="90594"/>
            <votos n="19" votos="8795"/>
            <votos n="31" votos="10678"/>
            <votos n="70" votos="20308"/>
            <votos n="23" votos="328035"/>
            <votos n="33" votos="19309"/>
            <votos n="16" votos="15082"/>
            <votos n="13" votos="1373206"/>
            <votos n="27" votos="11313"/>
        </votacao>
        <votacao estado="ce" brancos="272975" nulos="371781">
            <votos n="45" votos="804969"/>
            <votos n="19" votos="4113"/>
            <votos n="56" votos="12294"/>
            <votos n="23" votos="909402"/>
            <votos n="33" votos="10852"/>
            <votos n="16" votos="9136"/>
            <votos n="13" votos="872290"/>
            <votos n="27" votos="6160"/>
            <votos n="20" votos="5986"/>
            <votos n="43" votos="8398"/>
            <votos n="31" votos="6030"/>
            <votos n="70" votos="6473"/>
        </votacao>
        <votacao estado="df" brancos="18944" nulos="85422">
            <votos n="45" votos="391201"/>
            <votos n="19" votos="2240"/>
            <votos n="56" votos="13092"/>
            <votos n="23" votos="265838"/>
            <votos n="33" votos="1368"/>
            <votos n="16" votos="826"/>
            <votos n="13" votos="287579"/>
            <votos n="27" votos="908"/>
            <votos n="20" votos="1409"/>
            <votos n="43" votos="1739"/>
            <votos n="31" votos="487"/>
            <votos n="70" votos="455"/>
        </votacao>
        <votacao estado="es" brancos="104090" nulos="136664">
            <votos n="20" votos="2263"/>
            <votos n="45" votos="814535"/>
            <votos n="43" votos="3470"/>
            <votos n="19" votos="3210"/>
            <votos n="56" votos="18836"/>
            <votos n="31" votos="2336"/>
            <votos n="70" votos="2969"/>
            <votos n="23" votos="134675"/>
            <votos n="33" votos="6945"/>
            <votos n="16" votos="2631"/>
            <votos n="13" votos="263636"/>
            <votos n="27" votos="2505"/>
        </votacao>
        <votacao estado="go" brancos="235201" nulos="214929">
            <votos n="45" votos="1247510"/>
            <votos n="56" votos="34222"/>
            <votos n="19" votos="5142"/>
            <votos n="23" votos="195851"/>
            <votos n="33" votos="8801"/>
            <votos n="16" votos="6894"/>
            <votos n="13" votos="371175"/>
            <votos n="27" votos="3569"/>
            <votos n="20" votos="2842"/>
            <votos n="43" votos="7456"/>
            <votos n="31" votos="2471"/>
            <votos n="70" votos="5468"/>
        </votacao>
        <votacao estado="ma" brancos="284601" nulos="261234">
            <votos n="20" votos="4883"/>
            <votos n="43" votos="11015"/>
            <votos n="45" votos="736042"/>
            <votos n="19" votos="4221"/>
            <votos n="56" votos="24910"/>
            <votos n="31" votos="4638"/>
            <votos n="70" votos="8961"/>
            <votos n="23" votos="246268"/>
            <votos n="33" votos="11295"/>
            <votos n="16" votos="9534"/>
            <votos n="13" votos="444912"/>
            <votos n="27" votos="7030"/>
        </votacao>
        <votacao estado="mg" brancos="893201" nulos="983909">
            <votos n="45" votos="4225241"/>
            <votos n="56" votos="156826"/>
            <votos n="19" votos="25673"/>
            <votos n="23" votos="883377"/>
            <votos n="33" votos="36302"/>
            <votos n="16" votos="29689"/>
            <votos n="13" votos="2129100"/>
            <votos n="27" votos="19839"/>
            <votos n="20" votos="14230"/>
            <votos n="43" votos="28466"/>
            <votos n="31" votos="14139"/>
            <votos n="70" votos="25916"/>
        </votacao>
        <votacao estado="ms" brancos="57510" nulos="89937">
            <votos n="45" votos="520471"/>
            <votos n="56" votos="11981"/>
            <votos n="19" votos="3025"/>
            <votos n="23" votos="89951"/>
            <votos n="33" votos="3193"/>
            <votos n="16" votos="2207"/>
            <votos n="13" votos="210120"/>
            <votos n="27" votos="1665"/>
            <votos n="20" votos="812"/>
            <votos n="43" votos="2508"/>
            <votos n="31" votos="1425"/>
            <votos n="70" votos="2312"/>
        </votacao>
        <votacao estado="mt" brancos="88684" nulos="79957">
            <votos n="45" votos="663773"/>
            <votos n="56" votos="12012"/>
            <votos n="19" votos="2198"/>
            <votos n="23" votos="67668"/>
            <votos n="33" votos="3520"/>
            <votos n="16" votos="2024"/>
            <votos n="13" votos="149462"/>
            <votos n="27" votos="1591"/>
            <votos n="20" votos="1114"/>
            <votos n="43" votos="1924"/>
            <votos n="31" votos="810"/>
            <votos n="70" votos="1957"/>
        </votacao>
        <votacao estado="pa" brancos="150452" nulos="200372">
            <votos n="45" votos="1020868"/>
            <votos n="56" votos="30538"/>
            <votos n="19" votos="5387"/>
            <votos n="23" votos="165691"/>
            <votos n="33" votos="10772"/>
            <votos n="16" votos="8952"/>
            <votos n="13" votos="530722"/>
            <votos n="27" votos="5432"/>
            <votos n="20" votos="3273"/>
            <votos n="43" votos="6473"/>
            <votos n="31" votos="3028"/>
            <votos n="70" votos="5723"/>
        </votacao>
        <votacao estado="pb" brancos="221533" nulos="258592">
            <votos n="45" votos="541067"/>
            <votos n="19" votos="2885"/>
            <votos n="56" votos="15889"/>
            <votos n="23" votos="191878"/>
            <votos n="33" votos="7483"/>
            <votos n="16" votos="10039"/>
            <votos n="13" votos="402293"/>
            <votos n="27" votos="4309"/>
            <votos n="20" votos="2200"/>
            <votos n="43" votos="8411"/>
            <votos n="31" votos="3663"/>
            <votos n="70" votos="5363"/>
        </votacao>
        <votacao estado="pe" brancos="411026" nulos="537492">
            <votos n="45" votos="1637241"/>
            <votos n="56" votos="32391"/>
            <votos n="19" votos="7034"/>
            <votos n="23" votos="212165"/>
            <votos n="33" votos="18633"/>
            <votos n="16" votos="13966"/>
            <votos n="13" votos="890956"/>
            <votos n="27" votos="13001"/>
            <votos n="20" votos="9435"/>
            <votos n="43" votos="8336"/>
